# Generated by Django 5.2.11 on 2026-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parents', to='profiles.studentprofile'),
        ),
    ]
