# Generated by Django 5.2.11 on 2026-02-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('MARKS_ENTRY', 'Marks Entry'), ('ATTENDANCE_MARK', 'Attendance Mark'), ('RESULT_LOCK', 'Result Lock')], max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='audit_activ_user_id_1c38a1_idx'), models.Index(fields=['action_type'], name='audit_activ_action__abd890_idx'), models.Index(fields=['timestamp'], name='audit_activ_timesta_7eeebc_idx')],
            },
        ),
    ]
