# Generated by Django 5.2.11 on 2026-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('MARKS_ENTRY', 'Marks Entry'), ('ATTENDANCE_MARK', 'Attendance Mark'), ('RESULT_LOCK', 'Result Lock'), ('FAILED_LOGIN', 'Failed Login')], max_length=30),
        ),
    ]
