# Generated by Django 5.2.11 on 2026-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblock_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('MARKS_ENTRY', 'Marks Entry'), ('ATTENDANCE_MARK', 'Attendance Mark'), ('RESULT_LOCK', 'Result Lock'), ('FAILED_LOGIN', 'IP_BLOCKED')], max_length=30),
        ),
    ]
