# Generated by Django 5.2.11 on 2026-02-14 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_resultlock'),
        ('profiles', '0004_alter_parentprofile_address_alter_parentprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='markrecord',
            index=models.Index(fields=['student'], name='marks_markr_student_0428dc_idx'),
        ),
        migrations.AddIndex(
            model_name='markrecord',
            index=models.Index(fields=['subject'], name='marks_markr_subject_d00bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='markrecord',
            index=models.Index(fields=['exam_name'], name='marks_markr_exam_na_dda08f_idx'),
        ),
    ]
