# Generated by Django 5.2.11 on 2026-02-25 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_markrecord_marks_markr_student_0428dc_idx_and_more'),
        ('profiles', '0004_alter_parentprofile_address_alter_parentprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=100)),
                ('total_percentage', models.FloatField()),
                ('final_status', models.CharField(choices=[('PROMOTED', 'Promoted'), ('DETAINED', 'Detained'), ('REEXAM', 'Re-Exam')], max_length=20)),
                ('promoted_to_class', models.CharField(blank=True, max_length=50, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'exam_name')},
            },
        ),
    ]
