# Generated by Django 5.2.11 on 2026-03-01 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_promotionrecord'),
        ('profiles', '0004_alter_parentprofile_address_alter_parentprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markrecord',
            options={'ordering': ['student', 'subject']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_name', 'name']},
        ),
        migrations.AlterField(
            model_name='markrecord',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='markrecord',
            name='total_marks',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'class_name')},
        ),
        migrations.AddIndex(
            model_name='promotionrecord',
            index=models.Index(fields=['exam_name'], name='marks_promo_exam_na_9ec085_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionrecord',
            index=models.Index(fields=['class_name'], name='marks_promo_class_n_c45f70_idx'),
        ),
        migrations.AddIndex(
            model_name='resultlock',
            index=models.Index(fields=['class_name'], name='marks_resul_class_n_af37e6_idx'),
        ),
        migrations.AddIndex(
            model_name='resultlock',
            index=models.Index(fields=['exam_name'], name='marks_resul_exam_na_d0371d_idx'),
        ),
    ]
