# Generated by Django 5.2.11 on 2026-02-14 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('profiles', '0004_alter_parentprofile_address_alter_parentprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student'], name='attendance__student_bf8a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date'], name='attendance__date_337b1d_idx'),
        ),
    ]
